name: Deploy to S3

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                     # Set this to your desired AWS region
  S3_BUCKET_NAME: chigit      # Replace with your actual S3 bucket name

permissions:
  contents: read

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET_NAME }} --delete --exclude ".git/*"
